version: '3'

services: 
  backend:
    build: ./backend
    container_name: omd_backend
    restart: always
    volumes: 
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - 7000:3000
